### ISSUE TITLE
Minetest Gymnasium interface v0

### ISSUE THREAD

**Issue by garymm** [Astera-org/minetest#12]
- [x] Synchronous Interface to MT that's hooked up to a MQ
- [x] Gym interface for MQ & MT process starting and resetting
- [x] Lua extensions for defining rewards
- [x] Headless
- [x] Figure out why performance is so bad on MacOS (non-headless) now
- [ ] Properly shutdown xvfb when the environment is being shut down
- [x] Add some assertions to alert user when `minetest` binary launched by the gym client has died, and where to find the logs
- [x] Properly deal with arguments passed to the gym client (socket number, world name, ...)
- [ ] Increasing number of Ticks per seconds
- [ ] Update irrlicht headless branch. I currently don't have acess

**Comment by siboehm** [comment]
So far:
- [x] Synchronous Interface to MT that's hooked up to a MQ
- [x] Gym interface for MQ & MT process starting and resetting
- [ ] Lua extensions for defining rewards
- [ ] Headless

**Comment by garymm** [comment]
I tried running this inside a docker container on my mac and then connecting to it from the macOS host and I'm seeing crashes. I guess something is very wrong, so my current plan is:
 * Make sure the current thing works and then merge it
 * get a bazel build set up so I can be productive and use sanitizers
 * go back and fix a bunch of stuff
